version: "3.4"

volumes:
  database:

services:
  dairs:
    labels:
      - docker-volume-backup.stop-during-backup=dairs
    image: ghcr.io/derbaum941/dairs:latest
    volumes:
      - database:/home/node/dairs/src/db
      - ./general.json:/home/node/dairs/conf/general.json
      - ./credentials.json:/home/node/dairs/conf/credentials.json
    ports:
      - 9090:9090
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_STOP_CONTAINER_LABEL: dairs
      BACKUP_RETENTION_DAYS: 31
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_CRON_EXPRESSION: "0 0 4 * * 1"
    volumes:
      - database:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive
