name: Docker Image CI

on:
  push:
    branches:
    - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag dairs-bot:$(date +%s)
    
    - name: Login
      uses: docker/login-action@v1
      with: 
        registry: ${{ env.REGISTRY }}
        username: DerBaum941
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      if: github.repository == 'DerBaum941/DaIRS'
      with:
        context: .
        push: true
        tags: ghcr.io/derbaum941/dairs:v${{github.run_number}}
        labels: ${{ steps.meta.outputs.labels }}
