name: Docker Image CI

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dairs-bot:$(date +%s)
        git config --global user.name 'DerBaum941'
        git config --global user.email 'DerBaum941@users.noreply.github.com'
        git add .
        git commit -m 'Docker Build'
        git push origin docker-builds